#!/bin/sh
# render.sh — rebuild the report PDFs in this folder.
#
# [Managed by Superagent — regenerated by tools/render_report.py on every
#  render; do not hand-edit. Hand-tune a report in <stem>.tune.css (never
#  overwritten) and re-run this script.]
#
#   ./render.sh                   # render every *.html here (forced)
#   ./render.sh <stem> ...        # render selected reports (".html" optional)
#   ./render.sh --live [stem ...] # watch sources; re-render on change
set -eu

DIR=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
# Repo root embedded at generation time (render.sh is regenerated on every
# render, so a moved checkout self-heals on the next tool run); git fallback
# covers a render.sh invoked before that from inside the repo.
REPO="@@SUPERAGENT_REPO@@"
if [ ! -f "$REPO/pyproject.toml" ]; then
  REPO=$(git -C "$DIR" rev-parse --show-toplevel 2>/dev/null || true)
fi
if [ -z "$REPO" ] || [ ! -f "$REPO/pyproject.toml" ]; then
  echo "cannot locate the Superagent repo (re-run the renderer to refresh render.sh)" >&2
  exit 1
fi

render() { (cd "$REPO" && uv run python -m superagent.tools.render_report "$@"); }

render_set() {  # $1 = "--force" or "", $2... = stems (empty = all)
  flag=$1; shift
  count=0
  if [ "$#" -gt 0 ]; then
    for s in "$@"; do
      f="$DIR/${s%.html}.html"
      if [ -n "$flag" ]; then render "$flag" "$f" || true; else render "$f" || true; fi
      count=$((count + 1))
    done
  else
    for f in "$DIR"/*.html; do
      [ -e "$f" ] || continue
      if [ -n "$flag" ]; then render "$flag" "$f" || true; else render "$f" || true; fi
      count=$((count + 1))
    done
  fi
  if [ "$count" -eq 0 ]; then
    echo "no report HTML found in $DIR" >&2
    return 1
  fi
}

LIVE=0
if [ "${1:-}" = "--live" ]; then LIVE=1; shift; fi

if [ "$LIVE" -eq 0 ]; then
  render_set "--force" "$@"
  exit 0
fi

# --live: portable 1s mtime poll (BSD `ls -l -T` for second granularity,
# plain `ls -l` fallback). Renders lazily — the tool's own staleness check
# decides which PDFs actually rebuild.
stamp() { ls -l -T "$DIR"/*.html "$DIR"/*.css 2>/dev/null || ls -l "$DIR"/*.html "$DIR"/*.css 2>/dev/null || true; }
echo "watching $DIR — ctrl-c to stop"
prev=""
while :; do
  cur=$(stamp)
  if [ "$cur" != "$prev" ]; then
    render_set "" "$@" || true
    prev=$(stamp)
  fi
  sleep 1
done
