#!/usr/bin/env python3
"""Insert / refresh per-skill step indexes (perf-improvement-ideas.md QW-2 + MI-4).

For every skill markdown longer than `--min-lines` (default 100), this script
inserts a "Step index" block right after the YAML frontmatter:

```
## Step index

| # | Step | Lines |
|---|------|-------|
| 1 | Load configuration | 25-32 |
| 2 | Load last-check context | 34-44 |
...
```

The agent reads the frontmatter + step index (~40 lines), uses
`Read --offset --limit` to pull only the relevant step, and never loads the
full body. Long skills like `init.md`, `daily-update.md`, `monthly-review.md`,
`supertailor-review.md`, `add-source.md` benefit most.

Step boundaries are derived from H2 headings (`## N. <name>`).

Re-run after any skill edit; idempotent (replaces an existing step-index block
in place).
"""
from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path
from typing import NamedTuple

FRONTMATTER_RE = re.compile(r"^(---\s*\n.*?\n---\s*\n)", re.DOTALL)
H2_RE = re.compile(r"^(##\s+(.*))$", re.MULTILINE)
EXISTING_INDEX_RE = re.compile(
    r"\n## Step index\n.*?(?=\n##\s|\Z)",
    re.DOTALL,
)


class Step(NamedTuple):
    number: str
    title: str
    start_line: int
    end_line: int


def collect_steps(body: str, body_offset: int) -> list[Step]:
    """Find H2 headings in the body. Returns Step entries with absolute line numbers."""
    matches = list(H2_RE.finditer(body))
    if not matches:
        return []
    lines = body.splitlines()
    line_starts = [0]
    for line in lines:
        line_starts.append(line_starts[-1] + len(line) + 1)
    steps: list[Step] = []
    for i, m in enumerate(matches):
        char_offset = m.start()
        line_in_body = next(
            (idx for idx, start in enumerate(line_starts) if start > char_offset),
            len(lines),
        ) - 1
        next_offset = matches[i + 1].start() if i + 1 < len(matches) else len(body)
        next_line_in_body = next(
            (idx for idx, start in enumerate(line_starts) if start >= next_offset),
            len(lines),
        ) - 1
        if next_line_in_body <= line_in_body:
            next_line_in_body = line_in_body + 1
        title_full = m.group(2).strip()
        prefix_match = re.match(r"^(\d+\.?[a-z]?)\s+(.*)$", title_full)
        if prefix_match:
            number = prefix_match.group(1).rstrip(".")
            title = prefix_match.group(2)
        else:
            number = str(len(steps) + 1)
            title = title_full
        steps.append(Step(
            number=number,
            title=title,
            start_line=line_in_body + 1 + body_offset,
            end_line=next_line_in_body + body_offset,
        ))
    return steps


def render_index(steps: list[Step]) -> str:
    if not steps:
        return ""
    lines = [
        "",
        "## Step index",
        "",
        "_Auto-generated by `tools/add_step_index.py`. Re-run on any skill edit._",
        "",
        "| # | Step | Lines |",
        "|---|------|-------|",
    ]
    for s in steps:
        title = s.title.replace("|", "\\|")
        lines.append(f"| {s.number} | {title} | {s.start_line}-{s.end_line} |")
    lines.append("")
    return "\n".join(lines)


def has_step_index(body: str) -> bool:
    return bool(re.search(r"^##\s+Step index\s*$", body, re.MULTILINE))


def process_one(path: Path, min_lines: int) -> tuple[bool, str]:
    """Process one skill file. Returns (changed, reason)."""
    text = path.read_text()
    if len(text.splitlines()) < min_lines:
        return False, "below min-lines"
    fm_match = FRONTMATTER_RE.match(text)
    if not fm_match:
        return False, "no frontmatter"
    fm_end = fm_match.end()
    fm_text = fm_match.group(1)
    fm_line_count = len(fm_text.splitlines())
    after_fm = text[fm_end:]
    after_fm_clean = EXISTING_INDEX_RE.sub("", after_fm) if has_step_index(after_fm) else after_fm
    after_fm_clean = after_fm_clean.lstrip("\n")
    body_offset = fm_line_count
    steps = collect_steps(after_fm_clean, body_offset)
    if not steps:
        return False, "no H2 steps"
    rendered_index = render_index(steps).rstrip()
    new_body_clean = after_fm_clean
    insertion = rendered_index + "\n\n"
    new_text = fm_text + "\n" + insertion + new_body_clean
    if new_text == text:
        return False, "no change"
    path.write_text(new_text)
    return True, f"{len(steps)} steps indexed"


def parse_args(argv: list[str]) -> argparse.Namespace:
    parser = argparse.ArgumentParser(prog="add_step_index")
    parser.add_argument("--framework", type=Path,
                        default=Path(__file__).resolve().parent.parent)
    parser.add_argument("--min-lines", type=int, default=100,
                        help="Skip skills shorter than this (default 100).")
    parser.add_argument("--skill", type=str, default=None,
                        help="Process only the skill with this stem.")
    parser.add_argument("--check", action="store_true",
                        help="Only report which skills would change.")
    return parser.parse_args(argv)


def main(argv: list[str] | None = None) -> int:
    args = parse_args(argv if argv is not None else sys.argv[1:])
    skills_dir = args.framework / "skills"
    if not skills_dir.is_dir():
        print(f"No skills dir at {skills_dir}", file=sys.stderr)
        return 1
    paths = sorted(skills_dir.glob("*.md"))
    if args.skill:
        paths = [p for p in paths if p.stem == args.skill]
    changed = 0
    for path in paths:
        if args.check:
            text = path.read_text()
            if len(text.splitlines()) < args.min_lines:
                continue
            print(f"would touch  {path.name}")
            changed += 1
            continue
        ok, reason = process_one(path, args.min_lines)
        if ok:
            print(f"updated      {path.name} ({reason})")
            changed += 1
        else:
            print(f"skipped      {path.name} ({reason})")
    print(f"\n{changed} file(s) {'would be' if args.check else ''} updated.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
