#!/usr/bin/env python3
"""Insert / refresh step indexes (superagent/docs/_internal/perf-improvement-ideas.md QW-2 + MI-4).

Operates in two modes:

  --skill MODE (default)
    Walks every skill markdown under `superagent/skills/*.md` longer than
    `--min-lines` (default 100). Inserts a "Step index" block right after
    the YAML frontmatter.

  --file PATH (single-doc MODE)
    Process one arbitrary markdown file (e.g. a long doc under
    `superagent/docs/`). Inserts the step index right after the H1 title;
    YAML frontmatter is optional. Combine with `--numbered-only` to index
    only H2 headings that begin with a numeric prefix (`## 1. ...`),
    ignoring scaffolding H2s like `## Table of Contents`.

The block looks like:

```
## Step index

| # | Step | Lines |
|---|------|-------|
| 1 | Load configuration | 25-32 |
| 2 | Load last-check context | 34-44 |
...
```

The agent reads the top of the file (~40 lines for skills, ~50 for docs),
uses `Read --offset --limit` to pull only the relevant step, and never
loads the full body. Long skills (`init.md`, `daily-update.md`, ...) and
long docs (`contracts/`, `architecture.md`) benefit most.

Step boundaries are derived from H2 headings (`## N. <name>`).

Re-run after any edit; idempotent (replaces an existing step-index block
in place).
"""
from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path
from typing import NamedTuple

FRONTMATTER_RE = re.compile(r"^(---\s*\n.*?\n---\s*\n)", re.DOTALL)
H1_RE = re.compile(r"^(#\s+.+\n)")
H2_RE = re.compile(r"^(##\s+(.*))$", re.MULTILINE)
NUMBERED_PREFIX_RE = re.compile(r"^\d+\.?[a-z]?\s")

# Explicit start/end markers wrap the generated block so we can replace it
# atomically on every re-run — no regex-against-content fragility.
STEP_INDEX_BEGIN = "<!-- step-index:start -->"
STEP_INDEX_END = "<!-- step-index:end -->"
EXISTING_INDEX_RE = re.compile(
    re.escape(STEP_INDEX_BEGIN) + r".*?" + re.escape(STEP_INDEX_END) + r"\n*",
    re.DOTALL,
)
# Backwards-compatible match for unmarked legacy blocks (the old format).
# The legacy block is: `## Step index` heading + intro lines + a contiguous
# table (lines starting with `|`). We lazily skip non-table lines, then
# greedily consume the FIRST contiguous `|`-prefixed block, then stop. This
# avoids swallowing body paragraphs OR a tables-in-body that appears later.
LEGACY_INDEX_RE = re.compile(
    r"^## Step index\n(?:[^|].*\n|\n)*?(?:\|.*\n)+",
    re.MULTILINE,
)


class Step(NamedTuple):
    number: str
    title: str
    start_line: int
    end_line: int


def collect_steps(
    body: str,
    body_offset: int,
    numbered_only: bool = False,
) -> list[Step]:
    """Find H2 headings in the body. Returns Step entries with absolute line numbers.

    When `numbered_only` is True, H2s whose title does not begin with a
    numeric prefix (`## 1. Foo`, `## 2a Bar`, ...) are skipped — useful on
    long docs that have scaffolding H2s like `## Table of Contents`.
    """
    raw_matches = list(H2_RE.finditer(body))
    if numbered_only:
        matches = [
            m for m in raw_matches
            if NUMBERED_PREFIX_RE.match(m.group(2).strip())
        ]
    else:
        matches = raw_matches
    if not matches:
        return []
    lines = body.splitlines()
    line_starts = [0]
    for line in lines:
        line_starts.append(line_starts[-1] + len(line) + 1)
    steps: list[Step] = []
    for i, m in enumerate(matches):
        char_offset = m.start()
        line_in_body = next(
            (idx for idx, start in enumerate(line_starts) if start > char_offset),
            len(lines),
        ) - 1
        next_offset = matches[i + 1].start() if i + 1 < len(matches) else len(body)
        next_line_in_body = next(
            (idx for idx, start in enumerate(line_starts) if start >= next_offset),
            len(lines),
        ) - 1
        if next_line_in_body <= line_in_body:
            next_line_in_body = line_in_body + 1
        title_full = m.group(2).strip()
        prefix_match = re.match(r"^(\d+\.?[a-z]?)\s+(.*)$", title_full)
        if prefix_match:
            number = prefix_match.group(1).rstrip(".")
            title = prefix_match.group(2)
        else:
            number = str(len(steps) + 1)
            title = title_full
        steps.append(Step(
            number=number,
            title=title,
            start_line=line_in_body + 1 + body_offset,
            end_line=next_line_in_body + body_offset,
        ))
    return steps


def render_index(steps: list[Step]) -> str:
    if not steps:
        return ""
    lines = [
        STEP_INDEX_BEGIN,
        "",
        "## Step index",
        "",
        "_Auto-generated by `tools/add_step_index.py`. Re-run on any edit._",
        "",
        "| # | Step | Lines |",
        "|---|------|-------|",
    ]
    for s in steps:
        title = s.title.replace("|", "\\|")
        lines.append(f"| {s.number} | {title} | {s.start_line}-{s.end_line} |")
    lines.append("")
    lines.append(STEP_INDEX_END)
    return "\n".join(lines)


def has_step_index(body: str) -> bool:
    """True if the body carries either the marker-wrapped block or a legacy one."""
    if STEP_INDEX_BEGIN in body:
        return True
    return bool(re.search(r"^##\s+Step index\s*$", body, re.MULTILINE))


def strip_existing_index(body: str) -> str:
    """Remove a marker-wrapped block (preferred) or a legacy unmarked block."""
    if STEP_INDEX_BEGIN in body:
        return EXISTING_INDEX_RE.sub("", body)
    return LEGACY_INDEX_RE.sub("", body)


def process_one(
    path: Path,
    min_lines: int,
    numbered_only: bool = False,
    require_frontmatter: bool = True,
) -> tuple[bool, str]:
    """Process one markdown file. Returns (changed, reason).

    The "intro" — the prefix the step-index is inserted AFTER — is:
      * the YAML frontmatter, when present (skill-style files); else
      * the H1 title line, when present (doc-style files);
      * else position 0.

    `require_frontmatter` (default True for back-compat with the skill-walker
    behavior) refuses files lacking a YAML frontmatter; pass False when
    operating on plain docs.
    """
    text = path.read_text()
    if len(text.splitlines()) < min_lines:
        return False, "below min-lines"
    fm_match = FRONTMATTER_RE.match(text)
    if fm_match:
        intro = fm_match.group(1)
        intro_line_count = len(intro.splitlines())
    else:
        if require_frontmatter:
            return False, "no frontmatter"
        h1_match = H1_RE.match(text)
        if h1_match:
            intro = h1_match.group(1)
            intro_line_count = len(intro.splitlines())
        else:
            intro = ""
            intro_line_count = 0
    after_intro = text[len(intro):]
    after_clean = strip_existing_index(after_intro) if has_step_index(after_intro) else after_intro
    after_clean = after_clean.lstrip("\n")
    body_offset = intro_line_count
    steps = collect_steps(after_clean, body_offset, numbered_only=numbered_only)
    if not steps:
        return False, "no H2 steps"
    rendered_index = render_index(steps).rstrip()
    insertion = rendered_index + "\n\n"
    new_text = intro + "\n" + insertion + after_clean
    if new_text == text:
        return False, "no change"
    path.write_text(new_text)
    return True, f"{len(steps)} steps indexed"


def parse_args(argv: list[str]) -> argparse.Namespace:
    parser = argparse.ArgumentParser(prog="add_step_index")
    parser.add_argument("--framework", type=Path,
                        default=Path(__file__).resolve().parent.parent)
    parser.add_argument("--min-lines", type=int, default=100,
                        help="Skip files shorter than this (default 100).")
    parser.add_argument("--skill", type=str, default=None,
                        help="Process only the skill with this stem.")
    parser.add_argument("--file", type=Path, default=None,
                        help="Process a single arbitrary markdown file "
                             "(e.g. a long doc). YAML frontmatter is optional "
                             "in this mode.")
    parser.add_argument("--numbered-only", action="store_true",
                        help="Skip H2 headings without a numeric prefix "
                             "(useful on long docs that have scaffolding H2s "
                             "like 'Table of Contents').")
    parser.add_argument("--check", action="store_true",
                        help="Only report which files would change.")
    return parser.parse_args(argv)


def main(argv: list[str] | None = None) -> int:
    args = parse_args(argv if argv is not None else sys.argv[1:])
    if args.file is not None:
        if not args.file.exists():
            print(f"No such file: {args.file}", file=sys.stderr)
            return 1
        if args.check:
            text = args.file.read_text()
            if len(text.splitlines()) < args.min_lines:
                print(f"skipped      {args.file.name} (below min-lines)")
                return 0
            print(f"would touch  {args.file.name}")
            return 0
        ok, reason = process_one(
            args.file,
            args.min_lines,
            numbered_only=args.numbered_only,
            require_frontmatter=False,
        )
        if ok:
            print(f"updated      {args.file.name} ({reason})")
            return 0
        print(f"skipped      {args.file.name} ({reason})")
        return 0
    skills_dir = args.framework / "skills"
    if not skills_dir.is_dir():
        print(f"No skills dir at {skills_dir}", file=sys.stderr)
        return 1
    paths = sorted(skills_dir.glob("*.md"))
    if args.skill:
        paths = [p for p in paths if p.stem == args.skill]
    changed = 0
    for path in paths:
        if args.check:
            text = path.read_text()
            if len(text.splitlines()) < args.min_lines:
                continue
            print(f"would touch  {path.name}")
            changed += 1
            continue
        ok, reason = process_one(
            path, args.min_lines, numbered_only=args.numbered_only,
        )
        if ok:
            print(f"updated      {path.name} ({reason})")
            changed += 1
        else:
            print(f"skipped      {path.name} ({reason})")
    print(f"\n{changed} file(s) {'would be' if args.check else ''} updated.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
