# SPDX-FileCopyrightText: 2026 Mikhail Yurasov
# SPDX-License-Identifier: Apache-2.0
"""Claim a SimpleFin Bridge setup token into a long-lived Access URL.

Setup tokens are single-use. The claim is base64-decode -> POST. The
response body is an Access URL of the form `https://USER:PASS@host/path`,
which is the read-only credential we use thereafter.

Usage:
    uv run python -m superagent.tools.simplefin_claim <SETUP_TOKEN>
    # then verify by running the ingestor's probe:
    uv run python -m superagent.tools.ingest.simplefin --dry-run

The Access URL is written to
`workspace/_memory/sensitive/simplefin-credentials.yaml` with mode 600
before the script does anything else, so a downstream failure cannot
strand the (now-burned) credential.
"""
from __future__ import annotations

import argparse
import base64
import datetime as dt
import os
import sys
from pathlib import Path
from urllib.parse import urlparse
from urllib.request import Request, urlopen


def claim(setup_token: str) -> str:
    """POST the claim URL embedded in the setup token. Return the Access URL."""
    try:
        claim_url = base64.b64decode(setup_token).decode("ascii").strip()
    except Exception as exc:
        raise ValueError(f"setup token is not valid base64: {exc}") from exc
    parsed = urlparse(claim_url)
    if parsed.scheme not in ("http", "https") or not parsed.netloc:
        raise ValueError("setup token does not decode to an HTTP(S) URL")
    print(f"[claim] POST {parsed.scheme}://{parsed.netloc}{parsed.path[:24]}...")
    req = Request(
        claim_url,
        data=b"",
        method="POST",
        headers={
            "Content-Length": "0",
            "User-Agent": "superagent-simplefin-claim/0.1",
            "Accept": "*/*",
        },
    )
    with urlopen(req, timeout=30) as resp:
        body = resp.read().decode("ascii").strip()
    if not body.startswith("https://") or "@" not in body:
        raise RuntimeError(f"unexpected claim response: {body[:80]!r}")
    return body


def store(access_url: str, out_path: Path) -> None:
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(
        "# SimpleFin Bridge access credentials.\n"
        "# Long-lived URL with embedded HTTP Basic auth for read-only access\n"
        "# to connected institutions. Generated by claiming a one-time setup\n"
        "# token; the token cannot be reused.\n\n"
        f'access_url: "{access_url}"\n'
        f"claimed_at: {dt.datetime.now(tz=dt.UTC).isoformat().replace('+00:00', 'Z')}\n"
    )
    os.chmod(out_path, 0o600)


def main() -> int:
    parser = argparse.ArgumentParser(prog="simplefin-claim")
    parser.add_argument("token", help="Base64 setup token from SimpleFin Bridge.")
    parser.add_argument("--workspace", type=Path, default=None)
    parser.add_argument(
        "--force",
        action="store_true",
        help="Overwrite existing simplefin-credentials.yaml.",
    )
    args = parser.parse_args()

    framework = Path(__file__).resolve().parents[1]
    workspace = args.workspace or framework.parent / "workspace"
    out_path = workspace / "_memory" / "sensitive" / "simplefin-credentials.yaml"

    if out_path.exists() and not args.force:
        print(
            f"[claim] {out_path.relative_to(workspace.parent)} already exists; "
            "pass --force to replace it.",
            file=sys.stderr,
        )
        return 2

    try:
        access_url = claim(args.token)
    except Exception as exc:
        print(f"[claim] FAILED: {exc}", file=sys.stderr)
        return 1

    try:
        store(access_url, out_path)
    except Exception as exc:
        print(f"[store] FAILED: {exc}", file=sys.stderr)
        print(
            "Access URL was claimed but COULD NOT be written to disk. "
            "Capture it manually before this process exits:",
            file=sys.stderr,
        )
        print(f"  ACCESS_URL={access_url}", file=sys.stderr)
        return 3

    print(f"[claim] OK -> wrote {out_path.relative_to(workspace.parent)} (mode 600)")
    print("Next: uv run python -m superagent.tools.ingest.simplefin --dry-run")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
